# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a92165bfe3b93ddfa2759891699b20e"
name = "Trinity Billet Inventory"
application_url = "https://trinity-billet-inventory.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://trinity-billet-inventory.onrender.com",
  "https://trinity-billet-inventory.onrender.com/auth/callback"
]

[webhooks]
api_version = "2026-04"

[app_preferences]
url = "https://trinity-billet-inventory.onrender.com"
